[package]
name = "program-io"
version.workspace = true
edition.workspace = true

[dependencies]
gstd.workspace = true
scale-info.workspace = true
parity-scale-codec.workspace = true
gmeta.workspace = true
gear-lib.workspace = true
primitive-types.workspace = true
hex-literal.workspace = true
